"""Task-level operations: create, mark complete, trigger stage gate."""

from datetime import datetime, timezone

from sqlalchemy.orm import Session

from app.models.enums import EventType, ProjectStatus, TaskStatus
from app.models.onboarding_project import OnboardingProject
from app.models.task import Task
from app.schemas.task import TaskCreate
from app.services.event_service import log_event
from app.services.workflow_service import advance_stage


def create_task(db: Session, payload: TaskCreate) -> Task:
    """
    Create a new ad-hoc task on an existing project.

    Validates:
    - The project exists.
    - The project is not already completed.
    - The requested stage is either the current active stage or any prior stage
      (you cannot pre-create tasks for a stage the project hasn't reached yet,
      because future stage tasks are generated by the workflow engine).

    Logs a TASKS_GENERATED event for auditability.
    """
    from app.models.enums import STAGE_ORDER  # avoid circular at module top

    project: OnboardingProject | None = db.query(OnboardingProject).filter(
        OnboardingProject.id == payload.project_id
    ).first()

    if project is None:
        raise ValueError(f"Project {payload.project_id} not found.")

    if project.status == ProjectStatus.COMPLETED:
        raise ValueError(
            f"Project {payload.project_id} is already completed; "
            "tasks cannot be added."
        )

    # Only allow creating tasks for the current stage or earlier (past) stages.
    current_idx = STAGE_ORDER.index(project.current_stage)
    requested_idx = STAGE_ORDER.index(payload.stage)
    if requested_idx > current_idx:
        raise ValueError(
            f"Cannot create a task for stage '{payload.stage.value}': "
            f"the project is currently in '{project.current_stage.value}'. "
            "Future-stage tasks are generated automatically by the workflow engine."
        )

    task = Task(
        project_id=project.id,
        stage=payload.stage,
        title=payload.title,
        description=payload.description,
        assigned_to=payload.assigned_to,
        status=TaskStatus.NOT_STARTED,
        due_date=payload.due_date,
        required_for_stage_completion=payload.required_for_stage_completion,
        is_customer_required=payload.is_customer_required,
        requires_setup_data=payload.requires_setup_data,
    )
    db.add(task)
    db.flush()

    log_event(
        db,
        project_id=project.id,
        task_id=task.id,
        event_type=EventType.TASKS_GENERATED,
        message=(
            f"Ad-hoc task '{task.title}' created for stage '{payload.stage.value}' "
            f"by manual request."
        ),
    )

    db.commit()
    db.refresh(task)
    return task


def complete_task(
    db: Session,
    task: Task,
    project: OnboardingProject,
) -> tuple[Task, bool, object | None, bool]:
    """
    Mark a task as completed and trigger stage progression if possible.

    Returns (task, stage_advanced, new_stage, project_completed).
    """
    task.status = TaskStatus.COMPLETED
    task.updated_at = datetime.now(timezone.utc)
    db.flush()

    log_event(
        db,
        project_id=project.id,
        task_id=task.id,
        event_type=EventType.TASK_COMPLETED,
        message=f"Task '{task.title}' marked as completed.",
    )
    db.commit()

    # Reload project to pick up latest task states after commit.
    db.refresh(project)

    # Only attempt stage advancement when there is a pending template for the
    # next stage (i.e., project is not already completed/blocked beyond repair).
    from app.models.enums import ProjectStatus  # avoid circular at module level

    if project.status == ProjectStatus.COMPLETED:
        return task, False, None, True

    customer = project.customer
    advanced, new_stage, completed = advance_stage(db, project, customer.customer_type)

    return task, advanced, new_stage, completed
