/**
 * Canonical seed data for the public demo. All data is synthetic.
 * Used as the baseline; session-only mutations are applied as overlays and reset on refresh.
 */
import type {
  Customer,
  Project,
  ProjectDetail,
  Task,
  OnboardingEvent,
  RiskSignal,
  Recommendation,
} from '../types';

const BASE_DATE = '2025-03-01T00:00:00.000Z';

function iso(dayOffset: number): string {
  const d = new Date(BASE_DATE);
  d.setDate(d.getDate() + dayOffset);
  return d.toISOString();
}

// ─── Customers (3) ───────────────────────────────────────────────────────────

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 1,
    company_name: 'Acme Corp',
    customer_type: 'mid_market',
    industry: 'Technology',
    primary_contacts: null,
    onboarding_status: 'active',
    current_risk_level: 'low',
    health_summary: 'On track. Kickoff complete.',
    created_at: iso(-21),
    updated_at: iso(0),
  },
  {
    id: 2,
    company_name: 'Northgate Industries',
    customer_type: 'enterprise',
    industry: 'Manufacturing',
    primary_contacts: null,
    onboarding_status: 'active',
    current_risk_level: 'high',
    health_summary: 'Integration delayed. Two overdue tasks.',
    created_at: iso(-35),
    updated_at: iso(0),
  },
  {
    id: 3,
    company_name: 'Summit Labs',
    customer_type: 'smb',
    industry: 'Healthcare',
    primary_contacts: null,
    onboarding_status: 'active',
    current_risk_level: 'low',
    health_summary: 'Training nearly complete. Go-live in sight.',
    created_at: iso(-56),
    updated_at: iso(0),
  },
];

// ─── Projects (list shape, 3) ─────────────────────────────────────────────────

export const DEMO_PROJECTS: Project[] = [
  {
    id: 1,
    customer_id: 1,
    source_deal_id: null,
    playbook_id: 1,
    name: 'Acme Corp — Onboarding',
    current_stage: 'setup',
    status: 'active',
    risk_flag: false,
    risk_score: 28,
    risk_level: 'low',
    kickoff_date: iso(-14),
    target_go_live_date: iso(21),
    projected_go_live_date: iso(22),
    health_summary: null,
    next_best_action: 'Complete environment setup and send welcome pack.',
    notes: null,
    created_at: iso(-14),
    updated_at: iso(0),
  },
  {
    id: 2,
    customer_id: 2,
    source_deal_id: null,
    playbook_id: 2,
    name: 'Northgate Industries — Onboarding',
    current_stage: 'integration',
    status: 'at_risk',
    risk_flag: true,
    risk_score: 72,
    risk_level: 'high',
    kickoff_date: iso(-28),
    target_go_live_date: iso(14),
    projected_go_live_date: iso(19),
    health_summary: null,
    next_best_action: 'Escalate API credentials with customer. Two tasks overdue.',
    notes: null,
    created_at: iso(-28),
    updated_at: iso(0),
  },
  {
    id: 3,
    customer_id: 3,
    source_deal_id: null,
    playbook_id: 1,
    name: 'Summit Labs — Onboarding',
    current_stage: 'training',
    status: 'active',
    risk_flag: false,
    risk_score: 22,
    risk_level: 'low',
    kickoff_date: iso(-42),
    target_go_live_date: iso(7),
    projected_go_live_date: iso(8),
    health_summary: null,
    next_best_action: 'Run final training session and confirm go-live checklist.',
    notes: null,
    created_at: iso(-42),
    updated_at: iso(0),
  },
];

// ─── Project 1: Early (Kickoff/Setup), healthy ──────────────────────────────

const DEMO_TASKS_P1: Task[] = [
  {
    id: 101,
    project_id: 1,
    stage: 'kickoff',
    title: 'Kickoff call completed',
    description: 'Initial discovery and timeline alignment',
    assigned_to: null,
    owner_type: null,
    owner_id: null,
    status: 'completed',
    due_date: iso(-10),
    dependency_ids: null,
    blocker_flag: false,
    blocker_reason: null,
    completed_at: iso(-9),
    task_type: 'internal',
    required_for_stage_completion: true,
    is_customer_required: false,
    requires_setup_data: false,
    created_at: iso(-14),
    updated_at: iso(-9),
  },
  {
    id: 102,
    project_id: 1,
    stage: 'kickoff',
    title: 'Welcome pack sent',
    description: 'Docs and access instructions',
    assigned_to: null,
    owner_type: null,
    owner_id: null,
    status: 'completed',
    due_date: iso(-7),
    dependency_ids: null,
    blocker_flag: false,
    blocker_reason: null,
    completed_at: iso(-6),
    task_type: 'internal',
    required_for_stage_completion: true,
    is_customer_required: false,
    requires_setup_data: false,
    created_at: iso(-14),
    updated_at: iso(-6),
  },
  {
    id: 103,
    project_id: 1,
    stage: 'setup',
    title: 'Environment setup',
    description: 'Provision staging and prod',
    assigned_to: null,
    owner_type: null,
    owner_id: null,
    status: 'in_progress',
    due_date: iso(3),
    dependency_ids: null,
    blocker_flag: false,
    blocker_reason: null,
    completed_at: null,
    task_type: 'internal',
    required_for_stage_completion: true,
    is_customer_required: false,
    requires_setup_data: false,
    created_at: iso(-14),
    updated_at: iso(0),
  },
  {
    id: 104,
    project_id: 1,
    stage: 'setup',
    title: 'API credentials from customer',
    description: 'SSO or API keys for integration',
    assigned_to: null,
    owner_type: null,
    owner_id: null,
    status: 'not_started',
    due_date: iso(5),
    dependency_ids: null,
    blocker_flag: false,
    blocker_reason: null,
    completed_at: null,
    task_type: 'customer',
    required_for_stage_completion: true,
    is_customer_required: true,
    requires_setup_data: true,
    created_at: iso(-14),
    updated_at: iso(0),
  },
];

const DEMO_EVENTS_P1: OnboardingEvent[] = [
  { id: 1001, project_id: 1, task_id: 101, event_type: 'task_completed', message: 'Kickoff call completed', created_at: iso(-9) },
  { id: 1002, project_id: 1, task_id: 102, event_type: 'task_completed', message: 'Welcome pack sent', created_at: iso(-6) },
  { id: 1003, project_id: 1, task_id: null, event_type: 'project_advanced', message: 'Stage advanced to Setup', created_at: iso(-5) },
];

// ─── Project 2: Mid (Integration), at risk ───────────────────────────────────

const DEMO_TASKS_P2: Task[] = [
  {
    id: 201,
    project_id: 2,
    stage: 'integration',
    title: 'API credentials setup',
    description: 'Customer to provide API keys',
    assigned_to: null,
    owner_type: null,
    owner_id: null,
    status: 'overdue',
    due_date: iso(-5),
    dependency_ids: null,
    blocker_flag: true,
    blocker_reason: 'Waiting on customer security team',
    completed_at: null,
    task_type: 'customer',
    required_for_stage_completion: true,
    is_customer_required: true,
    requires_setup_data: true,
    created_at: iso(-28),
    updated_at: iso(0),
  },
  {
    id: 202,
    project_id: 2,
    stage: 'integration',
    title: 'Test data migration',
    description: 'Run migration in staging',
    assigned_to: null,
    owner_type: null,
    owner_id: null,
    status: 'in_progress',
    due_date: iso(2),
    dependency_ids: [201],
    blocker_flag: false,
    blocker_reason: null,
    completed_at: null,
    task_type: 'internal',
    required_for_stage_completion: true,
    is_customer_required: false,
    requires_setup_data: false,
    created_at: iso(-28),
    updated_at: iso(0),
  },
  {
    id: 203,
    project_id: 2,
    stage: 'integration',
    title: 'Integration walkthrough call',
    description: 'End-to-end validation with customer',
    assigned_to: null,
    owner_type: null,
    owner_id: null,
    status: 'not_started',
    due_date: iso(6),
    dependency_ids: null,
    blocker_flag: false,
    blocker_reason: null,
    completed_at: null,
    task_type: 'internal',
    required_for_stage_completion: true,
    is_customer_required: false,
    requires_setup_data: false,
    created_at: iso(-28),
    updated_at: iso(0),
  },
];

const DEMO_EVENTS_P2: OnboardingEvent[] = [
  { id: 2001, project_id: 2, task_id: null, event_type: 'risk_flag_added', message: 'Project flagged at risk', created_at: iso(-2) },
  { id: 2002, project_id: 2, task_id: 201, event_type: 'blocker_detected', message: 'API credentials setup blocked', created_at: iso(-1) },
];

const DEMO_RISK_SIGNALS_P2: RiskSignal[] = [
  { id: 301, project_id: 2, signal_type: 'overdue', description: 'API credentials setup is 5 days overdue', severity: 'high', created_at: iso(-1) },
  { id: 302, project_id: 2, signal_type: 'blocker', description: 'Customer dependency blocking integration', severity: 'high', created_at: iso(-1) },
];

const DEMO_RECOMMENDATIONS_P2: Recommendation[] = [
  { id: 401, project_id: 2, task_id: 201, action_type: 'escalate', priority: 1, dismissed: false, label: 'Escalate API credentials with customer', created_at: iso(0) },
  { id: 402, project_id: 2, task_id: null, action_type: 'simulate', priority: 2, dismissed: false, label: 'Run simulator to compare go-live scenarios', created_at: iso(0) },
];

// ─── Project 3: Late (Training / Go-live), nearly complete ────────────────────

const DEMO_TASKS_P3: Task[] = [
  {
    id: 301,
    project_id: 3,
    stage: 'kickoff',
    title: 'Kickoff completed',
    description: null,
    assigned_to: null,
    owner_type: null,
    owner_id: null,
    status: 'completed',
    due_date: iso(-35),
    dependency_ids: null,
    blocker_flag: false,
    blocker_reason: null,
    completed_at: iso(-34),
    task_type: null,
    required_for_stage_completion: true,
    is_customer_required: false,
    requires_setup_data: false,
    created_at: iso(-42),
    updated_at: iso(-34),
  },
  {
    id: 302,
    project_id: 3,
    stage: 'training',
    title: 'Admin training session',
    description: 'Platform admin walkthrough',
    assigned_to: null,
    owner_type: null,
    owner_id: null,
    status: 'completed',
    due_date: iso(-4),
    dependency_ids: null,
    blocker_flag: false,
    blocker_reason: null,
    completed_at: iso(-3),
    task_type: null,
    required_for_stage_completion: true,
    is_customer_required: false,
    requires_setup_data: false,
    created_at: iso(-42),
    updated_at: iso(-3),
  },
  {
    id: 303,
    project_id: 3,
    stage: 'training',
    title: 'End-user training',
    description: 'Final end-user session',
    assigned_to: null,
    owner_type: null,
    owner_id: null,
    status: 'in_progress',
    due_date: iso(2),
    dependency_ids: null,
    blocker_flag: false,
    blocker_reason: null,
    completed_at: null,
    task_type: null,
    required_for_stage_completion: true,
    is_customer_required: false,
    requires_setup_data: false,
    created_at: iso(-42),
    updated_at: iso(0),
  },
  {
    id: 304,
    project_id: 3,
    stage: 'go_live',
    title: 'Go-live checklist sign-off',
    description: 'Customer confirms readiness',
    assigned_to: null,
    owner_type: null,
    owner_id: null,
    status: 'not_started',
    due_date: iso(7),
    dependency_ids: null,
    blocker_flag: false,
    blocker_reason: null,
    completed_at: null,
    task_type: null,
    required_for_stage_completion: true,
    is_customer_required: true,
    requires_setup_data: false,
    created_at: iso(-42),
    updated_at: iso(0),
  },
];

const DEMO_EVENTS_P3: OnboardingEvent[] = [
  { id: 3001, project_id: 3, task_id: 302, event_type: 'task_completed', message: 'Admin training session', created_at: iso(-3) },
  { id: 3002, project_id: 3, task_id: null, event_type: 'project_advanced', message: 'Stage advanced to Training', created_at: iso(-4) },
];

// ─── Project details (full) ──────────────────────────────────────────────────

export const DEMO_PROJECT_DETAILS: Record<number, ProjectDetail> = {
  1: {
    ...DEMO_PROJECTS[0],
    tasks: DEMO_TASKS_P1,
    events: DEMO_EVENTS_P1,
    risk_signals: [],
    recommendations: [],
  },
  2: {
    ...DEMO_PROJECTS[1],
    tasks: DEMO_TASKS_P2,
    events: DEMO_EVENTS_P2,
    risk_signals: DEMO_RISK_SIGNALS_P2,
    recommendations: DEMO_RECOMMENDATIONS_P2,
  },
  3: {
    ...DEMO_PROJECTS[2],
    tasks: DEMO_TASKS_P3,
    events: DEMO_EVENTS_P3,
    risk_signals: [],
    recommendations: [],
  },
};

// ─── Demo IA: route paths (public, no auth) ───────────────────────────────────

export const DEMO_ROUTES = {
  root: '/demo',
  dashboard: '/demo/dashboard',
  projects: '/demo/projects',
  projectDetail: (id: number) => `/demo/projects/${id}`,
  projectTasks: (id: number) => `/demo/projects/${id}/tasks`,
  simulator: '/demo/simulator',
  playbooks: '/demo/playbooks',
  customers: '/demo/customers',
} as const;

export const DEMO_PROJECT_IDS = [1, 2, 3] as const;
export type DemoProjectId = (typeof DEMO_PROJECT_IDS)[number];
